(function(){
  const state={user:null, products:[], categories:[], orders:[]};
  const loginView=document.getElementById('loginView'), dashboard=document.getElementById('dashboardView'), loginMsg=document.getElementById('loginMsg');
  const modal=document.getElementById('modal'), modalContent=document.getElementById('modalContent');
  const showModal=html=>{modalContent.innerHTML=html;modal.hidden=false;}; const closeModal=()=>modal.hidden=true; document.getElementById('closeModal').onclick=closeModal;
  async function signIn(e){e.preventDefault(); if(!window.GLOVAERA?.client){loginMsg.textContent='Connect Supabase first by filling config.js.';return;} const fd=new FormData(e.target); const {data,error}=await GLOVAERA.client.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')}); if(error){loginMsg.textContent=error.message;return;} state.user=data.user; await boot();}
  async function boot(){loginView.hidden=true;dashboard.hidden=false;await refreshAll();}
  async function refreshAll(){
    const c=GLOVAERA.client; if(!c)return;
    const [p,cats,o]=await Promise.all([c.from('products').select('*').order('created_at',{ascending:false}),c.from('categories').select('*').order('name'),c.from('orders').select('*').order('created_at',{ascending:false})]);
    state.products=p.data||[];state.categories=cats.data||[];state.orders=o.data||[];renderOverview();renderProducts();renderCategories();renderOrders();
  }
  function renderOverview(){document.getElementById('statsGrid').innerHTML=[['Products',state.products.length],['Categories',state.categories.length],['Orders',state.orders.length],['Pending',state.orders.filter(o=>['new','confirmed','processing'].includes(o.status)).length]].map(([a,b])=>`<div class="stat-card"><span>${a}</span><strong>${b}</strong></div>`).join('');}
  function renderProducts(){document.getElementById('productAdminList').innerHTML=state.products.map(p=>`<div class="admin-row"><img src="${p.image_url||'logo.png'}"><div class="grow"><strong>${GLOVAERA.escapeHtml(p.name)}</strong><span>${GLOVAERA.escapeHtml(p.category||'')} · ${GLOVAERA.money(p.sale_price??p.price)} · Stock ${p.stock??0}</span></div><button class="btn btn-secondary small" data-edit-product="${p.id}">Edit</button><button class="btn btn-danger small" data-delete-product="${p.id}">Delete</button></div>`).join('') || '<div class="empty-state">No products yet.</div>';}
  function renderCategories(){document.getElementById('categoryAdminList').innerHTML=state.categories.map(c=>`<div class="admin-row"><div class="grow"><strong>${GLOVAERA.escapeHtml(c.name)}</strong><span>${GLOVAERA.escapeHtml(c.slug||'')}</span></div><button class="btn btn-secondary small" data-edit-category="${c.id}">Edit</button><button class="btn btn-danger small" data-delete-category="${c.id}">Delete</button></div>`).join('') || '<div class="empty-state">No categories yet.</div>';}
  function renderOrders(){document.getElementById('orderAdminList').innerHTML=state.orders.map(o=>`<div class="admin-order"><div class="admin-order-head"><strong>#${GLOVAERA.escapeHtml(String(o.id).slice(0,8))}</strong><span class="status ${o.status}">${o.status}</span></div><p>${GLOVAERA.escapeHtml(o.customer_name)} · ${GLOVAERA.escapeHtml(o.phone)}</p><p>${GLOVAERA.escapeHtml(o.address)}, ${GLOVAERA.escapeHtml(o.district)}</p><strong>${GLOVAERA.money(o.total)}</strong><div class="order-actions"><select data-order-status="${o.id}">${['new','confirmed','processing','shipped','delivered','cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></div></div>`).join('') || '<div class="empty-state">No orders yet.</div>';}
  function productForm(p={}){return `<form id="productForm" class="form-grid"><input type="hidden" name="id" value="${p.id||''}"><label>Name<input required name="name" value="${GLOVAERA.escapeHtml(p.name||'')}"></label><label>Category<select required name="category">${state.categories.map(c=>`<option ${c.name===p.category?'selected':''}>${GLOVAERA.escapeHtml(c.name)}</option>`).join('')}</select></label><label>Price<input required type="number" name="price" value="${p.price||0}"></label><label>Sale price<input type="number" name="sale_price" value="${p.sale_price??''}"></label><label>Stock<input required type="number" name="stock" value="${p.stock||0}"></label><label>Image URL<input name="image_url" value="${GLOVAERA.escapeHtml(p.image_url||'logo.png')}"></label><label>Upload image<input type="file" accept="image/*" name="image_file"></label><label class="full">Description<textarea name="description" rows="4">${GLOVAERA.escapeHtml(p.description||'')}</textarea></label><label><input type="checkbox" name="featured" ${p.featured?'checked':''}> Best seller</label><label><input type="checkbox" name="is_new" ${p.is_new?'checked':''}> New arrival</label><label><input type="checkbox" name="combo" ${p.combo?'checked':''}> Combo</label><button class="btn btn-primary full">Save product</button></form>`;}
  function categoryForm(c={}){return `<form id="categoryForm" class="form-grid"><input type="hidden" name="id" value="${c.id||''}"><label>Name<input required name="name" value="${GLOVAERA.escapeHtml(c.name||'')}"></label><label>Slug<input required name="slug" value="${GLOVAERA.escapeHtml(c.slug||'')}"></label><label class="full">Image URL<input name="image_url" value="${GLOVAERA.escapeHtml(c.image_url||'logo.png')}"></label><button class="btn btn-primary full">Save category</button></form>`;}
  async function saveProduct(e){e.preventDefault();const f=new FormData(e.target);let imageUrl=f.get('image_url')||'logo.png'; const file=f.get('image_file'); if(file && file.size){ const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'-'); const path=`${crypto.randomUUID()}-${safeName}`; const up=await GLOVAERA.client.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type}); if(up.error){alert(up.error.message);return;} imageUrl=GLOVAERA.client.storage.from('product-images').getPublicUrl(path).data.publicUrl; } const record={name:f.get('name'),category:f.get('category'),price:Number(f.get('price')),sale_price:f.get('sale_price')?Number(f.get('sale_price')):null,stock:Number(f.get('stock')),image_url:imageUrl,description:f.get('description'),featured:f.get('featured')==='on',is_new:f.get('is_new')==='on',combo:f.get('combo')==='on',active:true};const id=f.get('id');const q=id?GLOVAERA.client.from('products').update(record).eq('id',id):GLOVAERA.client.from('products').insert(record);const {error}=await q;if(error){alert(error.message);return;}closeModal();await refreshAll();}
  async function saveCategory(e){e.preventDefault();const f=new FormData(e.target);const record={name:f.get('name'),slug:f.get('slug'),image_url:f.get('image_url')||'logo.png'};const id=f.get('id');const q=id?GLOVAERA.client.from('categories').update(record).eq('id',id):GLOVAERA.client.from('categories').insert(record);const {error}=await q;if(error){alert(error.message);return;}closeModal();await refreshAll();}
  document.getElementById('loginForm').addEventListener('submit',signIn);document.getElementById('logoutBtn').onclick=async()=>{await GLOVAERA.client.auth.signOut();location.reload();};document.getElementById('addProductBtn').onclick=()=>{showModal('<h2>Add product</h2>'+productForm());document.getElementById('productForm').onsubmit=saveProduct;};document.getElementById('addCategoryBtn').onclick=()=>{showModal('<h2>Add category</h2>'+categoryForm());document.getElementById('categoryForm').onsubmit=saveCategory;};document.getElementById('refreshOrdersBtn').onclick=refreshAll;
  document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=true);document.getElementById('tab-'+btn.dataset.tab).hidden=false;});
  document.addEventListener('click',async e=>{const ep=e.target.closest('[data-edit-product]');if(ep){const p=state.products.find(x=>x.id===ep.dataset.editProduct);showModal('<h2>Edit product</h2>'+productForm(p));document.getElementById('productForm').onsubmit=saveProduct;return;}const dp=e.target.closest('[data-delete-product]');if(dp){if(confirm('Delete this product?')){const {error}=await GLOVAERA.client.from('products').delete().eq('id',dp.dataset.deleteProduct);if(error)alert(error.message);else refreshAll();}return;}const ec=e.target.closest('[data-edit-category]');if(ec){const c=state.categories.find(x=>x.id===ec.dataset.editCategory);showModal('<h2>Edit category</h2>'+categoryForm(c));document.getElementById('categoryForm').onsubmit=saveCategory;return;}const dc=e.target.closest('[data-delete-category]');if(dc){if(confirm('Delete this category?')){const {error}=await GLOVAERA.client.from('categories').delete().eq('id',dc.dataset.deleteCategory);if(error)alert(error.message);else refreshAll();}}});
  document.addEventListener('change',async e=>{const s=e.target.closest('[data-order-status]');if(!s)return;const {error}=await GLOVAERA.client.from('orders').update({status:s.value}).eq('id',s.dataset.orderStatus);if(error)alert(error.message);else refreshAll();});
  if(GLOVAERA.client) GLOVAERA.client.auth.getSession().then(({data})=>{if(data.session){state.user=data.session.user;boot();}});
})();
